### PR TITLE
add cython to requirements.txt

### PR DESCRIPTION
**Pull request by singlerider**
unable to complete fresh setup without cython installed

### CODE REVIEW

**Comment by flysonic10** [comment]
You should probably add this to setup.py, too.

**Comment by marionleborgne** [comment]
@flysonic10 actually this is not necessary, we're using `find_packages()`

**Comment by singlerider** [comment]
Code for OpenBCIBoard is directly from Chip's commit in the repo. No conflicts when I ran it. I recommend further testing, but it all looks good.

**Comment by marionleborgne** [comment]
`cython` is actually not a requirement (or at least should not be listed as a dependency in `requirements.txt`). I tested the install on a brand new OSX VM. No cython package needed.

@singlerider regarding the updated OpenBCI driver, can you point me to where you find the latest version?

I have been reluctant to merge this PR since none of that has been tested with the actual board. I am closing this PR until this is tested. Feel free to open a new issue and point me to the new OBCI driver code for future reference.

**Pull request closed without merging**
